### ISSUE TITLE
"Focus Group" opt in form

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#1]
Remember, this will be a part of the "Connect" auto-generated email when a user submits this form

https://www.figma.com/file/n3FWgrXUN44j0Q9HnoZU5Q/Loveology---Emails?node-id=92%3A48

**Comment by gitethanwoo** [comment]
I'm not sure what this issue is asking of me

**Comment by joenicolette** [comment]
The ask is to create an opt-in form that will be an outbound link from the autogenerated "get connected" email

The form would ask for:
- First Name
- Last Name
- Email
- Age Range
- Ethnicity
- Their Experience (Possibly)

**Comment by joenicolette** [comment]
Think of the "Create Account" flow. Very similar, but a one-pager instead of multiple steps

**Comment by gitethanwoo** [comment]
WIP https://www.figma.com/file/SrQ2YWcPssr67QrZXy4MkK/Design-Working-File?node-id=5780%3A117577

**Comment by joenicolette** [comment]
Looks good. Let's add the “Your Current Role” dropdown from the `Create Account` flow to gauge experience

**Comment by joenicolette** [comment]
@gitethanwoo

**Comment by gitethanwoo** [comment]
added

**Comment by gitethanwoo** [comment]
will push over to /issues
