### ISSUE TITLE
Expert Profile - Rachel Cruze

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#11]
- [x] Profile Photo/Vertical Crop
- [x] Summary
- [x] Bio
- [x] Applicable Links

**Comment by gitethanwoo** [comment]
- [ ] Profile photos

- [ ] Summary
- [ ] Bio
- [ ] Links

**Comment by gitethanwoo** [comment]
had to get a new photo for her. When I reviewed the current photo we had, it was too low-res. Obtained a new photo and photoshopped an arm.
