### ISSUE TITLE
Expert Quarterly Report

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#15]
Intent: **Create a design-forward, one-page PDF to send to our experts quarterly to drive interest, support, and future content creation.** 
The report should feature the following metrics, which will need to be templatized (Expert name, photo, and metrics can be easily edited)

Within x time frame, your videos on Loveology received:
- x amount of views
- x amount of clicks on your resources 
- x amount of shares, 
- Your top viewed videos
- x views on your expert page
- overall site traffic and percentage that’s going to you

**Comment by gitethanwoo** [comment]
https://www.figma.com/file/SrQ2YWcPssr67QrZXy4MkK/Design-Working-File?node-id=5974%3A119231

**Comment by oliviamshepherd** [comment]
@gitethanwoo did we finish this template for expert quarterly reports?
