### ISSUE TITLE
Wrap edits to Launch Newsletter

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#18]
https://www.figma.com/file/SrQ2YWcPssr67QrZXy4MkK/Design-Working-File?node-id=4417%3A93290

**Comment by joenicolette** [comment]
"The launch email feels like it’s written to a couple instead of a facilitator."
Consider:
1. **Audience**
2. **CTA**
3. Get them to experience LO. **What are we trying to get them to do?**

**Comment by gitethanwoo** [comment]
https://www.figma.com/file/SrQ2YWcPssr67QrZXy4MkK/Design-Working-File?node-id=4417%3A93290

**Comment by gitethanwoo** [comment]
just closing this - will reopen if review needs more
