### ISSUE TITLE
"Circle" usage - Resize expert headshots to remove excess headspace

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#25]
"The circles that have the author's face are using the old pictures with too much negative headspace. I know we agreed to change that but the old images are being used now. The small author head icons are already very small so the 1/3 extra space around their head makes the pic even smaller. We are not saying we need to make the circles bigger we just need to reduce the wasted space around their heads by zooming more in on the face in the same size circle."

<img width="247" alt="Screen Shot 2021-12-15 at 1 11 36 PM" src="https://user-images.githubusercontent.com/82427400/146242066-599ae0a2-cac0-4ba6-8b84-531a75561943.png">
<img width="289" alt="Screen Shot 2021-12-15 at 1 11 26 PM" src="https://user-images.githubusercontent.com/82427400/146242069-95100736-6304-476c-a919-8371f84ebdfd.png">

**Comment by gitethanwoo** [comment]
@1stevengrant is it possible to 'zoom in' further across all the author profile pictures for these avatars?

**Comment by gitethanwoo** [comment]
If not, I can edit all the photos and re-upload but I feel like there may be a different solution

**Comment by joenicolette** [comment]
Les/Ranjy specifically mentioned minimizing headroom for Gary Thomas and Dr. David Hawkins

**Comment by gitethanwoo** [comment]
@Angelinagwoo please make sure Gary Thomas and David Hawkins are corrected and look for any other headshots that don't conform to the 160-105 standard. If so, please correct and re-upload. My fault for not having a system in place at the start

**Comment by Angelinagwoo** [comment]
@gitethanwoo @joenicolette all expert photos have been scrubbed and updated to conform to 160-105 standard.
