### ISSUE TITLE
Expert Profiles - Update the profile photos, resources, and links

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#36]
If we haven't received content from an expert, we'll reach out to them.

Similar
- [x] Need a better picture for Ken Coleman and John Townsend. From Les "I think he’ll spaz if he sees this photo."
- [x] "Meg Meeker has no books."

**Comment by joenicolette** [comment]
Reopening to update Les and Leslie's new bio and resource list sent via Slack.

**Comment by Angelinagwoo** [comment]
@joenicolette Bio and all resources added. However, all the resources aren't showing up on their profile for some reason, even though they can be found if you search them in the "expert resources". Steven is working on correcting this.
