### ISSUE TITLE
Italicize all book names across the site

### ISSUE THREAD

**Issue by joenicolette** [loveology/design#37]

**Comment by Angelinagwoo** [comment]
Completed within expert bio's. @joenicolette, is there anywhere else they need to be italicized?

**Comment by joenicolette** [comment]
Cool! Still need to italicize book names on expert summaries. Feel free to open a ticket under the standard issues list to add this functionality. 


<img width="298" alt="Screen Shot 2022-01-04 at 8 19 57 PM" src="https://user-images.githubusercontent.com/82427400/148145692-28a2058c-3b5e-4b87-99bc-28653dab2721.png">
<img width="296" alt="Screen Shot 2022-01-04 at 8 19 52 PM" src="https://user-images.githubusercontent.com/82427400/148145696-7f0bf708-0534-4f73-b175-27421a9b67b0.png">

**Comment by Angelinagwoo** [comment]
@joenicolette All book titles italicized in Nova, not showing up correctly in Dev. Steven is working to correct it.
